import os
from crewai import Agent, Task, Crew, Process, LLM
from tools import CloudTools
from dotenv import load_dotenv

load_dotenv()

gemini_llm = LLM(
    model="gemini/gemini-2.5-flash",
    api_key=os.getenv("GEMINI_API_KEY"),
    temperature=0.2
)

# 2. Define Agents

# Agent 1: AWS Specialist
aws_agent = Agent(
    role='AWS Cloud Engineer',
    goal='Retrieve accurate status of EC2 instances and AWS billing data.',
    backstory='You are an expert in AWS infrastructure. You know how to query the AWS API to get a snapshot of running resources and costs.',
    tools=[CloudTools.get_aws_data],
    llm=gemini_llm,
    verbose=True
)

# Agent 2: GCP Specialist
gcp_agent = Agent(
    role='GCP Cloud Engineer',
    goal='Retrieve accurate status of Google Compute Engine instances.              ',
    backstory='You are a Google Cloud expert. You specialize in auditing GCP projects to list running virtual machines.',
    tools=[CloudTools.get_gcp_data],
    llm=gemini_llm,
    verbose=True
)

# Agent 3: Data Aggregator (The "A2A" Logic Hub)
analyst_agent = Agent(
    role='Senior Cloud Financial Analyst',
    goal='Synthesize data from AWS and GCP agents into a comprehensive financial report.',
    backstory='You are a financial analyst. You take raw technical data from cloud engineers, calculate total estimated spend, and format it into a readable executive summary.',
    llm=gemini_llm,
    verbose=True
)

# Agent 4: Email Reporter
email_agent = Agent(
    role='Executive Assistant',
    goal='Send the finalized report to the manager.',
    backstory='You are responsible for communicating critical updates to management. You take the final report and ensure it is delivered via email.',
    tools=[CloudTools.send_email],
    llm=gemini_llm,
    verbose=True
)

# 3. Define Tasks

# Task 1: Get AWS Data
aws_task = Task(
    description='Fetch the list of running EC2 instances and the total unblended cost for the last 30 days from AWS.',
    expected_output='A summary of AWS resources and costs.',
    agent=aws_agent
)

# Task 2: Get GCP Data
gcp_task = Task(
    description='Fetch the list of running Compute Engine instances from the configured GCP project.',
    expected_output='A summary of GCP resources.',
    agent=gcp_agent
)

# Task 3: Analyze and Report
# Note: In sequential process, this task will automatically receive context from Task 1 and Task 2.
analysis_task = Task(
    description=(
        "Review the AWS and GCP data provided by the previous agents. "
        "1. Summarize the total instance count across both clouds. "
        "2. Calculate the total estimated cost of the running machines."
        "3. Generate a complete report in **HTML format**. "
        "   - Use minimal CSS for styling (font-family: Arial, simple borders for tables). "
        "   - Create a summary table comparing AWS vs GCP instance counts and costs. "
        "   - Use <h3> tags for section headers. "
        "   - Ensure the total cost is highlighted in bold/color. "
        "Do NOT output Markdown; output raw HTML code only."
    ),
    expected_output='A complete HTML formatted report ready for email.',
    agent=analyst_agent,
    context=[aws_task, gcp_task] # Explicitly stating context for clarity
)

# Task 4: Email Delivery
email_task = Task(
    description='Send the report generated by the Analyst Agent to the manager via email.',
    expected_output='Confirmation that the email was sent.',
    agent=email_agent,
    context=[analysis_task]
)

# 4. Define Crew
cloud_crew = Crew(
    agents=[aws_agent, gcp_agent, analyst_agent, email_agent],
    tasks=[aws_task, gcp_task, analysis_task, email_task],
    process=Process.sequential, # Tasks execute in order, passing data down the chain
    verbose=True
)

if __name__ == "__main__":
    print("### Starting Multi-Cloud Monitoring Agents ###")
    result = cloud_crew.kickoff()
    print("\n\n########################")
    print("## Final Execution Log ##")
    print("########################\n")
    print(result)